# Generated by Django 5.2.5 on 2025-08-13 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_url_alter_post_region_alter_post_title'),
        ('blog', '0004_tag_post_tags'),
    ]

    operations = [
    ]
