# Generated by Django 5.2.5 on 2025-08-19 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_photo_alter_article_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.ImageField(blank=True, upload_to='article/%Y/%m/%d'),
        ),
    ]
