# Generated by Django 5.2.5 on 2025-08-19 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_article_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at', '-id']},
        ),
    ]
